name: CI
on: [push, pull_request]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
      - run: make ci